# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1fd1de1e0954399cdb1f674adec5031f9ec7c68b16be50848a69adb0aad483d8b5d64fa11143367003c955b18fd8d7735e99dd11047c061f8dc1f20d358274f

test:
  secret_key_base: 94ebcb7e03056cd643beff7b917e0d0f5ec3f6a991c287da5aefddb82e24d1e7ad181da07d556e14f6a1915b622108e1414f70b4de2f40511d5d270b8cf93116

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
